<?php 
    $virual = array(
        'ru'=>'Виртуальный тур',
        'en'=>'Virtual tour',
        'ua'=>'Віртуальний тур'
    )

?>
<h3><?php echo $this->item['title_'.$this->lang] ?></h3>
<div>
    <?php echo $this->item['full_'.$this->lang] ?>
</div>
<?php if($this->item['is_tour']) :?>
<div class="virtual-link">
    <a href="/virtual/view/object/<?php echo $this->item['tour_link']; ?>"><img src="/i/virtual_tour_<?php echo $this->lang ?>.png" alt="<?php echo $virual[$this->lang] ?>"/></a> 
</div>
<?php endif; ?>
