<?php
$translate = array(
    'ru' => array('Корпорация “Аллея смаку”', 'Украина, 36000, г. Полтава'),
    'ua' => array('Корпорація “Алея смаку”', 'Україна, 36000, м. Полтава'),
    'en' => array('Aleya Smaku korporation', '36000, Ukraine, Poltava'),
        )
?>
<div class="logos-list">
    <a href="/"><img src="/i/logos/smak.png"/></a>
    <?php
    foreach ($this->objects as $object):
        if (is_file($_SERVER['DOCUMENT_ROOT'] . '/i/logos/' . $object->id . '.png')):
            $title = 'title_'.$this->lang;
            ?>
            <a title='<?php echo $object->$title; ?>' href="/objects/view/url/<?php echo $object->tourLink ?>"><img src="/i/logos/<?php echo $object->id ?>.png"/></a>
            <?php
        endif;
    endforeach;
    ?>
    <a href="/objects/view/url/kafe-bar-evropa"><img src="/i/logos/bouling.png"/></a>
</div>
<div class="footer-info">
    <div class="container">
        <div class="lineelement footer-logo">
            <a href="/">
                <img src="/i/logo-small.png" alt="logo"/>
            </a>
        </div>
        <div class="lineelement address text">
            <p><?php echo $translate[$this->lang][0] ?></p>
            <p><?php echo $translate[$this->lang][1] ?></p>
        </div>
        <div class="lineelement contacts text">
            <p>+380 (532) 57-97-37</p>
            <p><a href="mailto:info@alleya-smaku.com.ua">info@alleya-smaku.com.ua</a></p>
        </div>
        <div class="lineelement right visa-block">
            <img src="/i/visa.png" alt="logo"/>
        </div>
    </div>
</div>