<?php
$translate = array(
    'ru' => array('Корпорация “Аллея смаку”', 'Украина, 36000, г. Полтава'),
    'ua' => array('Корпорація “Алея смаку”', 'Україна, 36000, м. Полтава'),
    'en' => array('Aleya Smaku korporation', '36000, Ukraine, Poltava'),
        );
$translate_art = array(
    'ru' => 'Разработано',
    'ua' => 'Розроблено',
    'en' => 'Created By'
)
?>
<div class="logos-list">
    
    <?php // echo $this->render("includes/logos_list.phtml"); ?>
    <?php echo $this->render("includes/logos_list_simple.phtml"); ?>
</div>
<div class="footer-info">
    <div class="container">
        <div class="lineelement footer-logo">
            <a href="<?php echo $this->urlMaker('') ?>">
                <img src="/i/logo-small.png" alt="logo"/>
            </a>
        </div>
        <div class="lineelement address text">
            <p><?php echo $translate[$this->lang][0] ?></p>
            <p><?php echo $translate[$this->lang][1] ?></p>
        </div>
        <div class="lineelement contacts text">
            <p>+380 (532) 57-97-37</p>
            <p><a href="mailto:info@alleya-smaku.com.ua">info@alleya-smaku.com.ua</a></p>
        </div>
        <div class="lineelement right visa-block">
            <img src="/i/visa.png" alt="logo"/>
        </div>
    </div>
    <div class="clear"></div>
    <div class="art">
        <?php echo $translate_art[$this->lang] ?> <a class="new-window" href="http://artvision.net.ua" title="ArtVision Studio">ArtVision Studio</a>
    </div>
</div>