<div class="logos-list">
    <img src="/i/logos/bochka.png"/>
    <img src="/i/logos/kozachka.png"/>
    <img src="/i/logos/evropa.png"/>
    <img src="/i/logos/rafinatto.png"/>
    <img src="/i/logos/nega.png"/>
    <img src="/i/logos/smak.png"/>
    <img src="/i/logos/poseidon.png"/>
    <img src="/i/logos/lotos.png"/>
    <img src="/i/logos/bouling.png"/>
    <img src="/i/logos/kasht.png"/>
</div>
<div class="footer-info">
    <div class="container">
        <div class="lineelement footer-logo">
            <a href="/">
                <img src="/i/logo-small.png" alt="logo"/>
            </a>
        </div>
        <div class="lineelement address text">
            <p>Корпорация “Аллея смаку”</p>
            <p>Украина, 36000, г. Полтава</p>
        </div>
        <div class="lineelement contacts text">
            <p>+380 (532) 57-97-37</p>
            <p><a href="mailto:info@alleya-smaku.com.ua">info@alleya-smaku.com.ua</a></p>
        </div>
        <div class="lineelement right visa-block">
            <img src="/i/visa.png" alt="logo"/>
        </div>
    </div>
</div>