<div class="jquery_image_carousel logos-container">
    <ul id ="logo-inner">
        <li><a href="/"><img src="/i/logos/AS.png"></a></li>
        <li><a title="Ресторанный комплекс &quot;Каштанова алея&quot;" href="/objects/view/url/restorannyy-kompleks-kashtanova-aleya"><img src="/i/logos/KA.png"></a></li>
        <li><a title="СПА-салон &quot;Лотос&quot;" href="/objects/view/url/spa-salon-lotos"><img src="/i/logos/Lotos.png"></a></li>
        <li><a title="Кафе-бар &quot;Бочка&quot;" href="/objects/view/url/kafe-bar-bochka"><img src="/i/logos/Bochka.png"></a></li>
        <li><a title="Ресторан &quot;Раффинато&quot;" href="http://alleya-grand.com.ua"><img src="/i/logos/AG.png"></a></li>
        <li><a title="Ресторан &quot;Раффинато&quot;" href="/objects/view/url/restoran-raffinato"><img src="/i/logos/Raff.png"></a></li>
        <li><a title="&quot;Нега&quot; бар" href="/objects/view/url/nega-bar"><img src="/i/logos/Nega.png"></a></li>
        <li><a title="Кафе-бар &quot;Европа&quot;" href="/objects/view/url/kafe-bar-evropa"><img src="/i/logos/Evropa.png"></a></li>
        <li><a title="Ресторан-бар &quot;Посейдон&quot;" href="/objects/view/url/restoran-bar-poseydon"><img src="/i/logos/Poseydon.png"></a></li>
        <li><a title="Ресторан &quot;Казачка&quot;" href="/objects/view/url/restoran-kazachka"><img src="/i/logos/Kazachka.png"></a></li>
        <li><a href="/objects/view/url/kafe-bar-evropa"><img src="/i/logos/Boulig.png"></a></li>
    </ul>
</div>
<div class="jcarousel-prev-horizontal logo-slider-arrow"></div>
<div class="jcarousel-next-horizontal logo-slider-arrow"></div>

