<?php
$translate = array(
    'ru' => array(
        'Новости' => 'Новости',
        'О компании' => 'О компании',
        'Заведения' => 'Заведения',
        'Контакты' => 'Контакты'
    ),
    'ua' => array(
        'Новости' => 'Новини',
        'О компании' => 'Про компанию',
        'Заведения' => 'Заклади',
        'Контакты' => 'Контакти'
    ),
    'en' => array(
        'Новости' => 'News',
        'О компании' => 'About',
        'Заведения' => 'Objects',
        'Контакты' => 'Contacts'
    ),
        )
?>
<div class="mainmenu">
    <div class="lineelement">
        <ul class="menu">
            <li><a href="/news"><?php echo $translate[$this->lang]['Новости'] ?></a></li>
            <li><a href="/about"><?php echo $translate[$this->lang]['О компании'] ?></a></li>
        </ul>
    </div>
    <div class="lineelement right">
        <ul class="menu">
            <li>
                <a href="#"><?php echo $translate[$this->lang]['Заведения'] ?></a>
                <ul>
                    <?php foreach ($this->objects as $object): ?>
                        <li><a href="/objects/view/url/<?php echo $object->tourLink ?>"><?php echo $object->title ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </li>
            <li><a href="/contacts"><?php echo $translate[$this->lang]['Контакты'] ?></a></li>
        </ul>
    </div>
    <div class="clear"></div>
</div>