<?php
$translate = array(
    'ru' => array(
        'Новости' => 'Новости',
        'О компании' => 'О компании',
        'Заведения' => 'Заведения',
        'Контакты' => 'Контакты'
    ),
    'ua' => array(
        'Новости' => 'Новини',
        'О компании' => 'Про компанію',
        'Заведения' => 'Заклади',
        'Контакты' => 'Контакти'
    ),
    'en' => array(
        'Новости' => 'News',
        'О компании' => 'About',
        'Заведения' => 'Objects',
        'Контакты' => 'Contacts'
    ),
        )
?>
<div class="mainmenu">
    <div class="lineelement">
        <ul class="menu">
            <li<?php if($this->controllerName=='news') echo ' class="active"' ?>><a href="<?php echo $this->urlMaker('/news') ?>"><?php echo $translate[$this->lang]['Новости'] ?></a></li>
            <li<?php if(in_array('about', $this->request)) echo ' class="active"' ?>><a href="<?php echo $this->urlMaker('/about') ?>"><?php echo $translate[$this->lang]['О компании'] ?></a></li>
        </ul>
    </div>
    <div class="lineelement right ddsmoothmenu" id="smoothmenu1">
        <ul class="menu">
            <li class="have-inner<?php if($this->controllerName=='objects') echo ' active' ?>">
                <a href="#"><?php echo $translate[$this->lang]['Заведения'] ?></a>
                <ul>
                    <?php foreach ($this->objects as $object): 
                        $title = 'title_'.$this->lang;
                    ?>
                        <li><a href="<?php echo $this->urlMaker('/objects/view/url/'.$object->tourLink) ?>"><?php echo $object->$title ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </li>
            <li<?php if(in_array('contacts', $this->request)) echo ' class="active"' ?>><a href="<?php echo $this->urlMaker('/contacts') ?>"><?php echo $translate[$this->lang]['Контакты'] ?></a></li>
        </ul>
    </div>
    <div class="clear"></div>
</div>