<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php
//echo (isset($this->title)?'<title>'.$this->title.'</title>':'');
        echo $this->headTitle($this->siteName);

        echo $this->headLink();

        echo $this->headScript();
        echo $this->headMeta();
        ?>

    </head>
    <body>
        <div class="container">
            <div class="header">
                <div class="header">
                    <div class="header_right">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <?php if(false) : ?>
                                <h4 class="pull-left username title"><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'index'), 'default', true); ?>">ADMIN AREA</a></h4>
                                <?php endif; ?>
                                <?php if ($this->loggedUser): ?>
                                    <ul class="pull-right nav">
                                        <li></li>
                                        <li class="dropdown">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Новости<b class="caret"></b></a>
                                            <ul class="dropdown-menu">
                                                <li><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'news'), 'default', true); ?>">Список новостей</a></li>
                                                <li><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'news', 'action' => 'create'), 'default', true); ?>">Добавить новость</a></li>
                                            </ul>
                                        </li>
                                        <li class="dropdown">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Объекты<b class="caret"></b></a>
                                            <ul class="dropdown-menu">
                                                <li><a href="<?php echo $this->url(array('module' => 'admin','controller'=>'objects'), 'default', true); ?>">Список объектов</a></li>
                                                <li><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'objects', 'action' => 'create'), 'default', true); ?>">Добавить объект</a></li>
                                            </ul>
                                        </li>
                                        <li><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'comments'), 'default', true); ?>">Комментарии</a></li>
                                        <li><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'staticpages'), 'default', true); ?>">Управление статическими страницами</a></li>
                                        
                                        <li class="dropdown">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Информационные блоки<b class="caret"></b></a>
                                            <ul class="dropdown-menu">
                                                <li><a href="<?php echo $this->url(array('module' => 'admin','controller'=>'info'), 'default', true); ?>">Список блоков</a></li>
                                                <li><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'info', 'action' => 'add'), 'default', true); ?>">Добавить блок</a></li>
                                            </ul>
                                        </li>
                                        
                                        <li class="dropdown">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Фотографии<b class="caret"></b></a>
                                            <ul class="dropdown-menu">
                                                <li><a href="<?php echo $this->url(array('module' => 'admin','controller'=>'photos'), 'default', true); ?>">Список фотографий</a></li>
                                                <li><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'photos', 'action' => 'add'), 'default', true); ?>">Добавить фотографии</a></li>
                                            </ul>
                                        </li>
                                        
                                        <li><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'logout'), 'default', true); ?>">Выйти</a></li>
                                    </ul>
                                <?php endif; ?>
                                <div class="clear"></div>
                            </div>
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
            <div class="container_12">
                <div class="grid_12">
                    <?php echo $this->layout()->content; ?>
                </div>
            </div>
        </div>
    </body>
</html>