<form method="post" action="#" enctype="multipart/form-data">
    <div class="files">
        <div id="div-for-clone">
            <div class="lineelement">
                <label> Выберте фотографию:
                    <input type="file" name="photo[]"/>
                </label>
                <br/>
                <label> Выберте превью:
                    <input type="file" name="preview[]"/>
                </label>
            </div>
            <div class="lineelement">
                <label for="contacts[]">Контакты
                    <input name="contacts[]" type="checkbox" value ="1"/>
                </label>
                <label for="contacts[]">Главная
                    <input name="main[]" type="checkbox" value ="1"/>
                </label>
                <label for="contacts[]">О компании
                    <input name="about[]" type="checkbox" value ="1"/>
                </label>
                <label for="contacts[]">Заведения
                    <input name="objects[]" type="checkbox" value ="1"/>
                </label>
            </div>
            
        </div>
    </div>
    <input type="submit" name="submit" value="Сохранить"/>
</form>
