<form method="post" action="#" enctype="multipart/form-data">
    <div class="files">
        <div id="div-for-clone">
            <div class="lineelement">
                <label> Выберте фотографию:
                    <input type="file" name="photo[]"/>
                </label>
                <br/>
                <label> Выберте превью:
                    <input type="file" name="preview[]"/>
                </label>
                <br/>
            <label> Описание(рус):
                <input class="photo-title" type="text" name="title_ru[]" value=""/>
            </label>
            <br/>
            <label> Описание(англ):
                <input class="photo-title" type="text" name="title_en[]" value=""/>
            </label>
            <br/>
            <label> Описание(укр):
                <input class="photo-title" type="text" name="title_ua[]" value=""/>
            </label>
            </div>
            
            <?php echo $this->render('page-list.phtml') ?>
            
        </div>
    </div>
    <input type="submit" name="submit" value="Сохранить"/>
</form>
