<form method="post" action="#" enctype="multipart/form-data">
    <div>
        <div>
            <img width="150px" height="100px" src="/i/galleries/previews/<?php echo $this->item->id . '.' . $this->item->extention ?>"/>
        </div>
        <div class="lineelement">
            <label> Выберте фотографию:
                <input type="file" name="photo"/>
            </label>
            <br/>
            <label> Выберте превью:
                <input type="file" name="preview"/>
            </label>
            <br/>
            <label> Описание(рус):
                <input class="photo-title" type="text" name="title_ru" value="<?php echo $this->item->title_ru ?>"/>
            </label>
            <br/>
            <label> Описание(англ):
                <input class="photo-title" type="text" name="title_en" value="<?php echo $this->item->title_en ?>"/>
            </label>
            <br/>
            <label> Описание(укр):
                <input class="photo-title" type="text" name="title_ua" value="<?php echo $this->item->title_ua ?>"/>
            </label>
        </div>
        <?php echo $this->render('page-list.phtml') ?>
    </div>
    <input type="submit" name="submit" value="Сохранить"/>
</form>
