<table class="table table-striped">
    <tr>
        <th>#</th>
        <th>Имя файла</th>
        <th>&nbsp;</th>
    </tr>
    <?php
    foreach ($this->items as $id => $item) {
        ?>
        <tr>
            <td><?php echo $id + 1; ?></td>
            <td><img width="150px" height="100px" src="/i/galleries/previews/<?php echo $item['id'] . '.' . $item['extention'] ?>"/></td>
            <td>
                <div class="table_actions">
                    <a href="<?php echo $this->url(array('action' => 'edit', 'id' => $item['id']), null); ?>" class="btn btn-success"><i class="icon-pencil icon-white"></i>Править</a>
                    <a href="<?php echo $this->url(array('action' => 'delete', 'id' => $item['id']), null); ?>" class="btn btn-danger delete-button"><i class="icon-trash icon-white"></i>Удалить</a>
                </div>
            </td>
        </tr>
        <?php
    }
    ?>
</table>

<?php echo $this->paginationControl($this->items, 'Sliding', 'pagination.phtml'); ?>

<a href="<?php echo $this->url(array('action' => 'add'), null); ?>" class="sexybutton sexysimple"><span class="add">Добавить фото</span></a>
