<table>
    <tr>
        <th>#</th>
        <th>Имя файла</th>
        <th>&nbsp;</th>
    </tr>
    <?php
    foreach ($this->items as $id => $item) {
        $item = $item->toArray();
        ?>
        <tr>
            <td><?php echo $id + 1; ?></td>
            <td><img width="150px" height="150px" src="/i/galleries/previews/<?php echo $item['id'].'.'.$item['extention'] ?>"/></td>
            <td>
                <div class="table_actions">
                    <a href="<?php echo $this->url(array('action' => 'edit', 'id' => $item['id']), null); ?>" class="sexybutton sexysimple"><span class="edit">Править</span></a>
                    <a href="<?php echo $this->url(array('action' => 'delete', 'id' => $item['id']), null); ?>" class="sexybutton sexysimple delete-button"><span class="delete">Удалить</span></a>
                </div>
            </td>
        </tr>
        <?php
    }
    ?>
</table>
<a href="<?php echo $this->url(array('action' => 'add'), null); ?>" class="sexybutton sexysimple"><span class="add">Добавить фото</span></a>
