<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php
        echo $this->headTitle();
        echo $this->headMeta();

        echo $this->headLink();

        echo $this->headScript();
        ?>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <?php echo $this->render("includes/mainmenu_static.phtml"); ?>
                <div class="logo">
                    <a href="/"><img src="/i/logo.png" alt="logo"/></a>
                </div>
                <div class="promo">
                    <img src="/i/promo.png" alt="promo"/>
                </div>
            </div>
            <div class="main-page">
                <div class="left-menu lineelement"><?php echo $this->render("includes/left-menu/" . $this->leftMenuPart); ?></div>
                <div class="content lineelement">
                    <?php echo $this->layout()->content; ?>
                </div>
                <div class="right-menu lineelement right">
                    <img src="/i/tel.png" alt="telephone"/>
                </div>
                <div class="clear"></div>
            </div>
            
            <div class="last-news-block">
                <?php  echo $this->render("includes/last-menu-block.phtml"); ?>
            </div>

            <?php
                echo $this->render("includes/footer.phtml");
            ?>
        </div>
    </body>
</html>
