<table class="table table-striped">
    <tr>
        <th>#</th>
        <th>Страница</th>
        <th>&nbsp;</th>
    </tr>
    <?php
    foreach ($this->items as $item) {
        ?>
        <tr>
            <td><?php echo $item['id']; ?></td>
            <td><?php echo $this->escape($item['title_ru']); ?></td>
            <td>
                <div class="table_actions">
                    <a href="<?php echo $this->url(array('action' => 'edit', 'id' => $item['id']), null); ?>" class="btn btn-success"><i class="icon-pencil icon-white"></i>Править</a>
                    <?php /* <a href="<?php echo $this->url(array('action'=>'delete', 'id'=>$item['id']), null);?>" class="sexybutton sexysimple"><span class="delete">Удалить</span></a> */ ?>
                </div>
            </td>
        </tr>
        <?php
    }
    ?>
</table>
<?php echo $this->paginationControl($this->items, 'Sliding', 'pagination.phtml'); ?>
<?php /*
  <a href="<?php echo $this->url(array('action'=>'create'), null);?>" class="sexybutton sexysimple"><span class="add">Добавить объект</span></a>
 */
?>