<?php
    $translate = array(
        'ru' => array(
            'Программа лояльности' => 'Программа лояльности', 
            'Вакансии' => 'Вакансии', 
            'Отзывы' => 'Отзывы', 
        ),
        'ua' => array(
            'Программа лояльности' => 'Програма лояльності', 
            'Вакансии' => 'Вакансії', 
            'Отзывы' => 'Відгуки', 
        ),
        'en' => array(
            'Программа лояльности' => 'Loyalty Program', 
            'Вакансии' => 'Carrier', 
            'Отзывы' => 'Feedbacks', 
        ),
    )
?>
<div class="top-venzel venzel"></div>
<a href="/programs"><?php echo $translate[$this->lang]['Программа лояльности'] ?></a>
<div class="left-menu-separator"></div>
<a href="/vacancies"><?php echo $translate[$this->lang]['Вакансии'] ?></a>
<div class="left-menu-separator"></div>
<a href="/backform"><?php echo $translate[$this->lang]['Отзывы'] ?></a>
<div class="bottom-venzel venzel"></div>
