<form action="#" method="post">
    <table class="table table-striped">
        <tr>
            <th>#</th>
            <th>Название объекта</th>
            <th>Порядок отображения</th>
            <th>&nbsp;</th>
        </tr>
        <?php
        foreach ($this->objects as $id => $item) {
            ?>
            <tr>
                <td><?php echo $id + 1; ?></td>
                <td><?php echo $this->escape($item['title_ru']); ?></td>
                <td><input type="text" name="order[<?php echo $item['id']; ?>]" value="<?php echo $this->escape($item['order']); ?>"/></td>
                <td>
                    <div class="table_actions">
                        <a href="<?php echo $this->url(array('action' => 'edit', 'id' => $item['id']), null); ?>" class="btn btn-success"><i class="icon-pencil icon-white"></i>Править</a>
                        <a href="<?php echo $this->url(array('action' => 'delete', 'id' => $item['id']), null); ?>" class="btn btn-danger delete-button"><i class="icon-trash icon-white"></i>Удалить</a>
                    </div>
                </td>
            </tr>
            <?php
        }
        ?>
        <tr>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td style="padding: 10px 0"><input class="lineelement right" type="submit" value="Сохранить порядок отображения"/></td>
        </tr>
    </table>
</form>
<?php echo $this->paginationControl($this->objects, 'Sliding', 'pagination.phtml'); ?>
<a href="<?php echo $this->url(array('action' => 'create'), null); ?>" class="sexybutton sexysimple"><span class="add">Добавить объект</span></a>