<table>
	<tr>
		<th>#</th>
		<th>Заголовок новости</th>
		<th>Дата</th>
		<th>&nbsp;</th>
	</tr>
	<?php
	foreach ($this->objects as $id=>$item)
	{
		?>
		<tr>
			<td><?php echo $id+1;?></td>
			<td><?php echo $this->escape($item['title']);?></td>
			<td>
				<div class="table_actions">
					<a href="<?php echo $this->url(array('action'=>'edit', 'id'=>$item['id']), null);?>" class="sexybutton sexysimple"><span class="edit">Править</span></a>
					<a href="<?php echo $this->url(array('action'=>'delete', 'id'=>$item['id']), null);?>" class="sexybutton sexysimple delete-button"><span class="delete">Удалить</span></a>
				</div>
			</td>
		</tr>
		<?php
	}
	?>
</table>
<?php echo $this->paginationControl($this->objects, 'Sliding', 'pagination.phtml'); ?>
<a href="<?php echo $this->url(array('action'=>'create'), null);?>" class="sexybutton sexysimple"><span class="add">Добавить объект</span></a>