<a href="/objects/view/url/<?php echo $this->object['tour_link'] ?>"><?php echo $this->object['title_'.$this->lang] ?></a>
<div id="flashcontent">

</div>
<script type="text/javascript">
        var so = new SWFObject("/swf/start.swf", "start", "907px", "675px", "10", "#fff");
        so.addVariable('object', "<?php echo $this->object['tour_link'] ?>" );
        so.addParam("menu", "false"); 
        so.addParam("wmode", "transparent"); 
        so.addParam('allowscriptaccess','always');
        so.allowFullScreen=true;
        so.write("flashcontent");
        function setHash(value)
        {
                window.location.hash = value;
        }
    // ]]>
</script>
