<?php
$translates = array(
    'resp' => array(
        'ru' => 'Добавить отзыв',
        'ua' => 'Додати відгук',
        'en' => 'Add Responce',
    ),
    'comment' => array(
        'ru' => 'Добавить комментарий',
        'ua' => 'Додати комментар',
        'en' => 'Add Comment',
    ),
    'name' => array(
        'ru' => 'Имя',
        'ua' => 'Им`я',
        'en' => 'Name',
    ),
    'mess' => array(
        'ru' => 'Сообщение',
        'ua' => 'Повідомлення',
        'en' => 'Message',
    ),
    'sym' => array(
        'ru' => 'Введите символы',
        'ua' => 'Введіть символи',
        'en' => 'Enter Symbols',
    ),
    'success_0' => array(
        'ru' => 'Ваш отзыв добавлен',
        'ua' => 'Ваш відгук додано',
        'en' => 'Your responce has been added',
    ),
    'success_1' => array(
        'ru' => 'Ваш коментарий добавлен',
        'ua' => 'Ваш коментарий додано',
        'en' => 'Your comment has been added',
    ),
    'add_comment' => array(
        'ru' => 'прокоментровать',
        'ua' => 'прокоментувати',
        'en' => 'add comment',
    ),
);
?>
<div class="full-form-content">
    <?php if ($this->showSuccessMessage): ?>
        <div class="success-comment">
            <?php echo $translates['success_' . $this->parent_id][$this->lang] ?>
        </div>
    <?php endif; ?>
    <div class="comment-header">
        <a href="#" id="show-contact-form"><?php echo $translates['resp'][$this->lang] ?></a>
    </div>
    <form method="post" action="" class="contact-form">
        <input type="hidden" name="parent_id" value="0" id="parent_id">
        <div class="contact-form-block">
            <div class="lineelement label">
                <label for="name"><?php echo $translates['name'][$this->lang] ?>:</label>
            </div>
            <div class="lineelement">
                <?php echo $this->form->getElement('name'); ?>
            </div>
            <div class="clear"></div>
            <div class="errors">
                <?php
                if ($this->real_parent_id == 0) {
                    $errors = $this->form->getElement('name')->getMessages();
                    if (count($errors)) {
                        foreach ($errors as $error) {
                            echo '<p>' . $error . '</p>';
                        }
                    }
                }
                ?>
            </div>
        </div>
        <div class="contact-form-block">
            <div class="lineelement label">
                <label for="email">E-mail:</label>
            </div>
            <div class="lineelement">
                <?php echo $this->form->getElement('email'); ?>
            </div>
            <div class="clear"></div>
            <div class="errors">
                <?php
                if ($this->real_parent_id == 0) {
                    $errors = $this->form->getElement('email')->getMessages();
                    if (count($errors)) {
                        foreach ($errors as $error) {
                            echo '<p>' . $error . '</p>';
                            break;
                        }
                    }
                }
                ?>
            </div>
        </div>
        <div class="contact-form-block">
            <div class="lineelement label">
                <label for="text"><?php echo $translates['mess'][$this->lang] ?>:</label>
            </div>
            <div class="lineelement">
                <?php echo $this->form->getElement('text'); ?>
            </div>
            <div class="clear"></div>
            <div class="errors">
                <?php
                if ($this->real_parent_id == 0) {
                    $errors = $this->form->getElement('text')->getMessages();
                    if (count($errors)) {
                        foreach ($errors as $error) {
                            echo '<p>' . $error . '</p>';
                        }
                    }
                }
                ?>
            </div>
        </div>
        <div class="contact-form-block">

            <div class="lineelement label">
                <label for="text"><?php echo $translates['sym'][$this->lang] ?>:</label>
            </div>

            <div class="lineelement captcha">
                <?php echo $this->form->captcha; ?>
            </div>
            <div class="clear"></div>
            <div class="errors">
                <?php
                if ($this->real_parent_id == 0) {
                    $errors = $this->form->getElement('captcha')->getMessages();
                    if (count($errors)) {
                        foreach ($errors as $error) {
                            echo '<p>' . $error . '</p>';
                        }
                    }
                }
                ?>
            </div>
        </div>
        <div class="lineelement right add-comment-button contact-form-block">
            <button class="btn"><?php echo $translates['resp'][$this->lang] ?></button>
        </div>
        <div class="clear"></div>
    </form>

    <?php
    if ($this->real_parent_id == 0) {
        echo $this->render('includes/comment-form.phtml');
    }
    ?>

</div>

<div id="comments-block">
    <?php foreach ($this->comments as $comment): ?>
        <div class="comment">
            <h4><?php echo $comment['name'] . '(' . date('d-m-Y H:i', strtotime($comment['created_ts'])) . ')'; ?>:</h4>
            <div><?php echo $comment['message']; ?></div>
            <a href="#" post_id="<?php echo $comment['id'] ?>" class="add-comment"><?php echo $translates['add_comment'][$this->lang] ?></a>
            <?php
            if ($comment['id'] == $this->real_parent_id) {
                echo $this->render('includes/comment-form.phtml');
            }
            ?>
            <div class="subcomments">
                <?php foreach (models_CommentMapper::getAllByParentId($comment['id']) as $subcomment): ?>
                    <div class="comment">
                        <h4><?php echo $subcomment->name . '(' . date('d-m-Y H:i', strtotime($subcomment->created_ts)) . ')'; ?>:</h4>
                        <div><?php echo $subcomment->message; ?></div>
                    </div>
                <?php endforeach; ?>
            </div>
            <div class="clear"></div>
        </div>
    <?php endforeach; ?>

    <?php echo $this->paginationControl($this->comments, 'Sliding', 'pagination_' . $this->lang . '.phtml'); ?>
</div>